var msg = 'Loading...';
var msg2 = 'Loading..';
var msg3 = 'Loading.';
var msg4 = 'Loaded';
var msg5 = '       ';
var interfaceUp1 = "|||||||||||||||||||||||||||||||||||||| LoaApp ||||||||||||||||||||||||||||||||||||||||||||";
var interfaceUp2 = " "
var interfaceUp3 = "Hi"
var text1 = "print node Y.js for next, Print node N.js for end"

console.log(msg) 
console.warn(msg2);
console.warn(msg3);
console.warn(msg4);
console.log(msg5)
console.log(interfaceUp1);
console.log(interfaceUp2);
console.log(interfaceUp3);
console.warn(text1)
console.log("        ")
console.log("||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||");